version: '3.7'
services:
  node:
    cap_add:
      - ALL
    image: woohanx/kfk_node:v4
    networks:
      - testNet1
    tty: true
    command: python3 /home/apps/script/launch_kfk.py
    environment:
      nodeNum:
networks:
  testNet1:
