version: '3'
services:
  node:
    image: woohanx/kfk_node:v3
    networks:
      - testNet3
    tty: true
    command: python3 /home/apps/script/launch_kfk.py
    environment:
      nodeNum:
networks:
  testNet3:
